

# This file was *autogenerated* from the file p1553_list_only_mass_collision_toy_r22.sage
from sage.all_cmdline import *   # import sage library

_sage_const_193 = Integer(193); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_44 = Integer(44); _sage_const_8 = Integer(8); _sage_const_9 = Integer(9); _sage_const_29 = Integer(29); _sage_const_4096 = Integer(4096); _sage_const_155322 = Integer(155322); _sage_const_103 = Integer(103); _sage_const_0 = Integer(0); _sage_const_16 = Integer(16); _sage_const_80 = Integer(80); _sage_const_4 = Integer(4); _sage_const_10 = Integer(10)
import json
import random
import statistics
from collections import Counter, defaultdict


F = GF(_sage_const_193 )
E = EllipticCurve(F, [_sage_const_2 , _sage_const_3 ])
P = E(_sage_const_1 , _sage_const_44 )
R = PolynomialRing(F, "x")
x = R.gen()

DEGREE = _sage_const_8 
ENDPOINT_SCALARS = list(range(_sage_const_1 , _sage_const_9 ))
FIFTH_SCALARS = list(range(_sage_const_9 , _sage_const_29 ))
CANDIDATE_COUNT = _sage_const_4096 
RANDOM_SEED = _sage_const_155322 

assert P.order() == _sage_const_103 

endpoints = [a * P for a in ENDPOINT_SCALARS]
fifth_points = [q * P for q in FIFTH_SCALARS]
endpoint_x = [F(A[_sage_const_0 ]) for A in endpoints]
psi_num = prod(x - value for value in endpoint_x)


def point_x(point):
    assert not point.is_zero()
    return F(point[_sage_const_0 ])


sources = []
evaluated_x = set(endpoint_x)
for endpoint_scalar, A in zip(ENDPOINT_SCALARS, endpoints):
    for fifth_scalar, Q in zip(FIFTH_SCALARS, fifth_points):
        plus_x = point_x(A + Q)
        minus_x = point_x(A - Q)
        evaluated_x.add(plus_x)
        evaluated_x.add(minus_x)
        sources.append(
            {
                "endpoint_scalar": endpoint_scalar,
                "fifth_scalar": fifth_scalar,
                "plus_x": plus_x,
                "minus_x": minus_x,
            }
        )


def complete_key(denominator, source):
    plus = psi_num(source["plus_x"]) / denominator(source["plus_x"])
    minus = psi_num(source["minus_x"]) / denominator(source["minus_x"])
    return int(plus + minus), int(plus * minus)


def evaluate_candidate(denominator):
    fibers = defaultdict(list)
    for source in sources:
        fibers[complete_key(denominator, source)].append(
            [source["endpoint_scalar"], source["fifth_scalar"]]
        )
    sizes = sorted((len(values) for values in fibers.values()), reverse=True)
    return {
        "distinct_keys": len(fibers),
        "max_fiber": sizes[_sage_const_0 ],
        "sum_squared_fibers": sum(size * size for size in sizes),
        "fiber_sizes": sizes,
        "fibers": fibers,
    }


def geometric_fiber_min_support(denominator):
    minimum = DEGREE + _sage_const_1 
    witnesses = []
    for value in F:
        fiber_poly = psi_num - value * denominator
        finite_support = fiber_poly.squarefree_part().degree() if fiber_poly else _sage_const_0 
        infinity_support = _sage_const_1  if fiber_poly.degree() < DEGREE else _sage_const_0 
        support = finite_support + infinity_support
        if support < minimum:
            minimum = support
            witnesses = [int(value)]
        elif support == minimum:
            witnesses.append(int(value))
    pole_support = denominator.squarefree_part().degree()
    if pole_support < minimum:
        minimum = pole_support
        witnesses = ["infinity"]
    elif pole_support == minimum:
        witnesses.append("infinity")
    return int(minimum), witnesses[:_sage_const_16 ]


identity_fibers = defaultdict(list)
for source in sources:
    plus = source["plus_x"]
    minus = source["minus_x"]
    key = (int(plus + minus), int(plus * minus))
    identity_fibers[key].append(
        [source["endpoint_scalar"], source["fifth_scalar"]]
    )

rng = random.Random(int(RANDOM_SEED))
best = None
distinct_counts = []
valid_candidates = _sage_const_0 
attempts = _sage_const_0 

while valid_candidates < CANDIDATE_COUNT:
    attempts += _sage_const_1 
    coefficients = [F(rng.randrange(_sage_const_193 )) for _ in range(DEGREE)]
    denominator = x**DEGREE + sum(coefficients[i] * x**i for i in range(DEGREE))
    if gcd(psi_num, denominator) != _sage_const_1 :
        continue
    if any(denominator(value) == _sage_const_0  for value in evaluated_x):
        continue
    derivative_num = psi_num.derivative() * denominator - psi_num * denominator.derivative()
    if derivative_num == _sage_const_0 :
        continue

    result = evaluate_candidate(denominator)
    valid_candidates += _sage_const_1 
    distinct_counts.append(result["distinct_keys"])
    score = (
        result["distinct_keys"],
        -result["sum_squared_fibers"],
        -result["max_fiber"],
    )
    if best is None or score < best["score"]:
        best = {
            "score": score,
            "denominator": denominator,
            "coefficients_low_to_high": [int(value) for value in coefficients] + [_sage_const_1 ],
            "result": result,
        }

assert best is not None

source_count = len(sources)
best_result = best["result"]
compression_ratio = source_count / best_result["distinct_keys"]
min_support, min_support_values = geometric_fiber_min_support(best["denominator"])

collision_fibers = []
for key, values in sorted(
    best_result["fibers"].items(), key=lambda item: (-len(item[_sage_const_1 ]), item[_sage_const_0 ])
):
    if len(values) > _sage_const_1 :
        collision_fibers.append(
            {
                "key": list(key),
                "multiplicity": len(values),
                "sources": values,
            }
        )


def expected_sampled_mass_coverage(sample_count):
    total = source_count
    uncovered = sum(
        (size / total) * ((_sage_const_1  - size / total) ** sample_count)
        for size in best_result["fiber_sizes"]
    )
    return _sage_const_1  - uncovered


universe = _sage_const_193 **_sage_const_2 
random_key_expected_distinct = universe * (_sage_const_1  - (_sage_const_1  - _sage_const_1  / universe) ** source_count)

sorted_counts = sorted(distinct_counts)


def percentile(numerator, denominator):
    index = (len(sorted_counts) - _sage_const_1 ) * numerator // denominator
    return int(sorted_counts[index])


decision = (
    "RETAIN_LIST_ONLY_COMPRESSION_FOR_REVIEW"
    if best_result["distinct_keys"] <= _sage_const_80 
    else "REJECT_NO_TWOFOLD_LIST_ONLY_COMPRESSION"
)

report = {
    "schema": "crypto.autoresearch.exact_toy_report.v1",
    "report_id": "P1553-LIST-ONLY-MASS-COLLISION-TOY-R22-REPORT",
    "date": "2026-07-19",
    "classification": ["toy", "exact", "model-bound", "novelty-unverified"],
    "field": _sage_const_193 ,
    "curve_order": int(E.order()),
    "subgroup_order": int(P.order()),
    "degree": DEGREE,
    "endpoint_scalars": ENDPOINT_SCALARS,
    "fifth_scalars": FIFTH_SCALARS,
    "endpoint_block_size": len(ENDPOINT_SCALARS),
    "source_count": source_count,
    "candidate_count": CANDIDATE_COUNT,
    "candidate_attempts": attempts,
    "random_seed": RANDOM_SEED,
    "psi_numerator": str(psi_num),
    "best_denominator": str(best["denominator"]),
    "best_denominator_coefficients_low_to_high": best["coefficients_low_to_high"],
    "best_distinct_complete_keys": best_result["distinct_keys"],
    "best_compression_ratio": compression_ratio,
    "best_collision_excess": source_count - best_result["distinct_keys"],
    "best_max_fiber": best_result["max_fiber"],
    "best_sum_squared_fibers": best_result["sum_squared_fibers"],
    "best_geometric_fiber_min_support": min_support,
    "best_geometric_fiber_min_support_values": min_support_values,
    "best_collision_fibers": collision_fibers,
    "sampled_mass_coverage": {
        "R_source_count_over_4": expected_sampled_mass_coverage(source_count // _sage_const_4 ),
        "R_source_count_over_2": expected_sampled_mass_coverage(source_count // _sage_const_2 ),
        "R_distinct_key_count": expected_sampled_mass_coverage(
            best_result["distinct_keys"]
        ),
    },
    "candidate_distinct_key_summary": {
        "minimum": int(sorted_counts[_sage_const_0 ]),
        "p10": percentile(_sage_const_1 , _sage_const_10 ),
        "median": int(statistics.median(sorted_counts)),
        "p90": percentile(_sage_const_9 , _sage_const_10 ),
        "maximum": int(sorted_counts[-_sage_const_1 ]),
    },
    "controls": {
        "identity_psi_distinct_complete_keys": len(identity_fibers),
        "identity_psi_max_fiber": max(len(values) for values in identity_fibers.values()),
        "random_key_universe": universe,
        "random_key_expected_distinct": random_key_expected_distinct,
    },
    "decision": decision,
    "breakthrough": False,
    "shoup_bound_improvement": False,
    "scope": (
        "Finite regular-chart search only. No asymptotic containment, target, "
        "R10, rank, factor-log, descent, lower-bound, or breakthrough claim."
    ),
}

print(json.dumps(report, indent=_sage_const_2 , sort_keys=True, default=lambda value: int(value)))

