

# This file was *autogenerated* from the file p1553_list_only_mass_collision_holdout_r22d.sage
from sage.all_cmdline import *   # import sage library

_sage_const_193 = Integer(193); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_44 = Integer(44); _sage_const_9 = Integer(9); _sage_const_29 = Integer(29); _sage_const_49 = Integer(49); _sage_const_147 = Integer(147); _sage_const_140 = Integer(140); _sage_const_100 = Integer(100); _sage_const_41 = Integer(41); _sage_const_188 = Integer(188); _sage_const_123 = Integer(123); _sage_const_182 = Integer(182); _sage_const_46 = Integer(46); _sage_const_103 = Integer(103); _sage_const_0 = Integer(0); _sage_const_106 = Integer(106); _sage_const_1p5 = RealNumber('1.5'); _sage_const_8 = Integer(8)
import json
from collections import defaultdict


F = GF(_sage_const_193 )
E = EllipticCurve(F, [_sage_const_2 , _sage_const_3 ])
P = E(_sage_const_1 , _sage_const_44 )
R = PolynomialRing(F, "x")
x = R.gen()

ENDPOINT_SCALARS = list(range(_sage_const_1 , _sage_const_9 ))
TRAINING_FIFTH_SCALARS = list(range(_sage_const_9 , _sage_const_29 ))
HOLDOUT_FIFTH_SCALARS = list(range(_sage_const_29 , _sage_const_49 ))
DENOMINATOR_COEFFICIENTS = [_sage_const_147 , _sage_const_140 , _sage_const_100 , _sage_const_41 , _sage_const_188 , _sage_const_123 , _sage_const_182 , _sage_const_46 , _sage_const_1 ]

assert P.order() == _sage_const_103 

endpoints = [a * P for a in ENDPOINT_SCALARS]
endpoint_x = [F(A[_sage_const_0 ]) for A in endpoints]
psi_num = prod(x - value for value in endpoint_x)
psi_den = sum(F(value) * x**i for i, value in enumerate(DENOMINATOR_COEFFICIENTS))


def point_x(point):
    assert not point.is_zero()
    return F(point[_sage_const_0 ])


def evaluate(fifth_scalars):
    fibers = defaultdict(list)
    pole_sources = []
    for endpoint_scalar, A in zip(ENDPOINT_SCALARS, endpoints):
        for fifth_scalar in fifth_scalars:
            Q = fifth_scalar * P
            plus_x = point_x(A + Q)
            minus_x = point_x(A - Q)
            if psi_den(plus_x) == _sage_const_0  or psi_den(minus_x) == _sage_const_0 :
                pole_sources.append([endpoint_scalar, fifth_scalar])
                continue
            plus = psi_num(plus_x) / psi_den(plus_x)
            minus = psi_num(minus_x) / psi_den(minus_x)
            key = (int(plus + minus), int(plus * minus))
            fibers[key].append([endpoint_scalar, fifth_scalar])

    source_count = len(ENDPOINT_SCALARS) * len(fifth_scalars)
    collision_fibers = [
        (key, values) for key, values in fibers.items() if len(values) > _sage_const_1 
    ]
    zero_collision_fibers = [
        (key, values) for key, values in collision_fibers if key[_sage_const_1 ] == _sage_const_0 
    ]
    return {
        "source_count": source_count,
        "evaluated_source_count": source_count - len(pole_sources),
        "pole_sources": pole_sources,
        "distinct_complete_keys": len(fibers),
        "compression_ratio": (
            (source_count - len(pole_sources)) / len(fibers) if fibers else _sage_const_0 
        ),
        "collision_excess": sum(len(values) - _sage_const_1  for _, values in collision_fibers),
        "zero_branch_collision_excess": sum(
            len(values) - _sage_const_1  for _, values in zero_collision_fibers
        ),
        "max_fiber": max((len(values) for values in fibers.values()), default=_sage_const_0 ),
        "collision_fiber_count": len(collision_fibers),
    }


training = evaluate(TRAINING_FIFTH_SCALARS)
holdout = evaluate(HOLDOUT_FIFTH_SCALARS)

decision = (
    "RETAIN_HOLDOUT_COMPRESSION_FOR_REVIEW"
    if not holdout["pole_sources"]
    and holdout["distinct_complete_keys"] <= _sage_const_106 
    and holdout["compression_ratio"] >= _sage_const_1p5 
    else "REJECT_HOLDOUT_TRANSFER_BELOW_1P5_OR_POLE"
)

report = {
    "schema": "crypto.autoresearch.exact_toy_report.v1",
    "report_id": "P1553-LIST-ONLY-MASS-COLLISION-HOLDOUT-R22D-REPORT",
    "date": "2026-07-19",
    "classification": [
        "toy",
        "exact",
        "fresh-holdout",
        "model-bound",
        "novelty-unverified",
    ],
    "field": _sage_const_193 ,
    "subgroup_order": int(P.order()),
    "degree": _sage_const_8 ,
    "endpoint_scalars": ENDPOINT_SCALARS,
    "training_fifth_scalars": TRAINING_FIFTH_SCALARS,
    "holdout_fifth_scalars": HOLDOUT_FIFTH_SCALARS,
    "psi_numerator": str(psi_num),
    "psi_denominator": str(psi_den),
    "training": training,
    "holdout": holdout,
    "decision": decision,
    "breakthrough": False,
    "shoup_bound_improvement": False,
    "scope": (
        "One fixed finite-field holdout. No asymptotic containment, target, "
        "R10, rank, factor-log, descent, lower-bound, or breakthrough claim."
    ),
}

print(json.dumps(report, indent=_sage_const_2 , sort_keys=True, default=lambda value: int(value)))

