#!/usr/bin/env python3
"""Scan every pencil generated by retained R45 degree-nine block sections."""

import collections
import itertools
import json

import p1553_primitive_degree_nine_rank_search_r44 as r44


CATALOG_PATH = "p1553_rank_minor_guided_partition_search_report_r45.json"
PRIME = r44.r38.PRIME
SUBGROUP_ORDER = r44.r38.SUBGROUP_ORDER
STEP = 42
BLOCK_SIZE = 9
SELECTED_LENGTH = 81


def dot(left, right):
    return sum(a * b for a, b in zip(left, right)) % PRIME


def block_mask(block):
    mask = 0
    for offset in block:
        mask |= 1 << offset
    return mask


def plucker_key(first, second):
    coordinates = [
        (first[left] * second[right] - first[right] * second[left]) % PRIME
        for left in range(9)
        for right in range(left + 1, 9)
    ]
    first_nonzero = next(value for value in coordinates if value)
    inverse = pow(first_nonzero, -1, PRIME)
    return bytes(value * inverse % PRIME for value in coordinates)


def projective_labels(first_values, second_values, inverses):
    labels = []
    for first, second in zip(first_values, second_values):
        if first == 0:
            if second == 0:
                raise AssertionError("pencil has a subgroup base point")
            labels.append(PRIME)
        else:
            labels.append(second * inverses[first] % PRIME)
    return labels


def multiplicity_histogram(labels):
    fiber_counts = collections.Counter(labels)
    histogram = collections.Counter(fiber_counts.values())
    return fiber_counts, {
        str(multiplicity): histogram[multiplicity]
        for multiplicity in sorted(histogram)
    }


def run():
    with open(CATALOG_PATH, encoding="utf-8") as input_file:
        r45_report = json.load(input_file)
    partitions = r45_report["rank_eight_partition_catalog"]
    blocks = sorted(
        {
            tuple(block)
            for partition in partitions
            for block in partition
        }
    )
    if len(partitions) != 281 or len(blocks) != 807:
        raise AssertionError("unexpected R45 catalog dimensions")
    if any(len(block) != BLOCK_SIZE or sum(block) != r44.MAGIC_SUM for block in blocks):
        raise AssertionError("catalog block contract failed")

    section_to_block = {}
    for block in blocks:
        vector, _ = r44.block_section(block, 0, STEP)
        if vector in section_to_block and section_to_block[vector] != block:
            raise AssertionError("one section vector names two block divisors")
        section_to_block[vector] = block
    sections = sorted(section_to_block)
    if len(sections) != len(blocks):
        raise AssertionError("catalog sections did not deduplicate by divisor")

    scalar_embeddings = r44.SECTION_EMBEDDINGS
    section_values = [
        tuple(dot(section, embedding) for embedding in scalar_embeddings)
        for section in sections
    ]
    selected_scalars = tuple(
        STEP * (offset - 40) % SUBGROUP_ORDER
        for offset in range(SELECTED_LENGTH)
    )
    selected_values = [
        tuple(values[scalar] for scalar in selected_scalars)
        for values in section_values
    ]
    masks = [block_mask(section_to_block[section]) for section in sections]
    inverses = [0] + [pow(value, -1, PRIME) for value in range(1, PRIME)]

    zero_set_checks = []
    for index, block in enumerate(section_to_block[section] for section in sections):
        selected_zero_offsets = {
            offset
            for offset, value in enumerate(selected_values[index])
            if value == 0
        }
        subgroup_zero_count = sum(value == 0 for value in section_values[index])
        zero_set_checks.append(
            selected_zero_offsets == set(block)
            and subgroup_zero_count == BLOCK_SIZE
        )

    pair_overlap_histogram = collections.Counter()
    disjoint_section_pairs = 0
    duplicate_pencil_pairs = 0
    pencil_keys = set()
    complete_fiber_histogram = collections.Counter()
    complete_coverage_histogram = collections.Counter()
    maximum_selected_multiplicity_histogram = collections.Counter()
    best = None
    survivors = []

    for first_index, second_index in itertools.combinations(range(len(sections)), 2):
        overlap = (masks[first_index] & masks[second_index]).bit_count()
        pair_overlap_histogram[overlap] += 1
        if overlap:
            continue
        disjoint_section_pairs += 1
        key = plucker_key(sections[first_index], sections[second_index])
        if key in pencil_keys:
            duplicate_pencil_pairs += 1
            continue
        pencil_keys.add(key)

        subgroup_labels = projective_labels(
            section_values[first_index],
            section_values[second_index],
            inverses,
        )
        subgroup_counts, subgroup_histogram = multiplicity_histogram(
            subgroup_labels
        )
        maximum_subgroup_multiplicity = max(subgroup_counts.values())
        if maximum_subgroup_multiplicity > BLOCK_SIZE:
            raise AssertionError("degree-nine pencil has an oversized subgroup fiber")

        selected_labels = [subgroup_labels[scalar] for scalar in selected_scalars]
        selected_counts, selected_histogram = multiplicity_histogram(
            selected_labels
        )
        complete_fibers = sum(
            multiplicity == BLOCK_SIZE
            for multiplicity in selected_counts.values()
        )
        complete_coverage = BLOCK_SIZE * complete_fibers
        maximum_selected_multiplicity = max(selected_counts.values())
        collision_pairs = sum(
            multiplicity * (multiplicity - 1) // 2
            for multiplicity in selected_counts.values()
        )
        complete_fiber_histogram[complete_fibers] += 1
        complete_coverage_histogram[complete_coverage] += 1
        maximum_selected_multiplicity_histogram[
            maximum_selected_multiplicity
        ] += 1

        score = (
            complete_coverage,
            collision_pairs,
            maximum_selected_multiplicity,
        )
        record = {
            "first_block": list(section_to_block[sections[first_index]]),
            "second_block": list(section_to_block[sections[second_index]]),
            "complete_nine_point_fibers": complete_fibers,
            "complete_coverage": complete_coverage,
            "collision_pairs": collision_pairs,
            "maximum_selected_multiplicity": maximum_selected_multiplicity,
            "selected_multiplicity_histogram": selected_histogram,
            "subgroup_multiplicity_histogram": subgroup_histogram,
        }
        if best is None or score > best[0] or (
            score == best[0]
            and (
                record["first_block"],
                record["second_block"],
            )
            < (
                best[1]["first_block"],
                best[1]["second_block"],
            )
        ):
            best = (score, record)
        if complete_fibers == 9:
            survivors.append(record)

    total_section_pairs = len(sections) * (len(sections) - 1) // 2
    checks = {
        "r45_partition_catalog_count": len(partitions) == 281,
        "unique_block_count": len(blocks) == 807,
        "unique_section_count": len(sections) == 807,
        "all_section_zero_sets_match_blocks": all(zero_set_checks),
        "all_section_pairs_accounted": sum(pair_overlap_histogram.values())
        == total_section_pairs,
        "all_disjoint_pairs_accounted": len(pencil_keys)
        + duplicate_pencil_pairs
        == disjoint_section_pairs,
        "all_unique_pencils_scored": sum(complete_fiber_histogram.values())
        == len(pencil_keys),
        "no_nine_fiber_survivor": not survivors,
    }
    if not all(checks.values()):
        raise AssertionError("catalog pencil fiber scan check failed")

    return {
        "schema": "p1553.catalog_pencil_fiber_scan.r46.v1",
        "classification": [
            "toy",
            "exact",
            "exhaustive-catalog-scan",
            "model-bound",
            "novelty-unverified",
        ],
        "field_prime": PRIME,
        "subgroup_order": SUBGROUP_ORDER,
        "selected_interval_length": SELECTED_LENGTH,
        "catalog": {
            "rank_eight_partitions": len(partitions),
            "block_instances": sum(len(partition) for partition in partitions),
            "unique_blocks": len(blocks),
            "unique_sections": len(sections),
        },
        "pair_scan": {
            "total_section_pairs": total_section_pairs,
            "block_overlap_histogram": {
                str(overlap): pair_overlap_histogram[overlap]
                for overlap in sorted(pair_overlap_histogram)
            },
            "disjoint_section_pairs": disjoint_section_pairs,
            "duplicate_pencil_pairs": duplicate_pencil_pairs,
            "unique_basepoint_free_catalog_pencils": len(pencil_keys),
        },
        "fiber_results": {
            "complete_nine_point_fiber_histogram": {
                str(count): complete_fiber_histogram[count]
                for count in sorted(complete_fiber_histogram)
            },
            "complete_coverage_histogram": {
                str(coverage): complete_coverage_histogram[coverage]
                for coverage in sorted(complete_coverage_histogram)
            },
            "maximum_selected_multiplicity_histogram": {
                str(multiplicity): maximum_selected_multiplicity_histogram[
                    multiplicity
                ]
                for multiplicity in sorted(maximum_selected_multiplicity_histogram)
            },
            "required_complete_fibers": 9,
            "required_complete_coverage": 81,
            "survivors": survivors,
            "best_witness": best[1],
        },
        "checks": checks,
        "limits": [
            "the scan is exhaustive only over pencils generated by sections in the retained R45 catalog",
            "R45 itself used budgeted closures and did not enumerate every equal-sum block",
            "a catalog pencil with fewer than nine complete fibers does not exclude another primitive degree-nine pencil",
            "no asymptotic family, target locator, R10 output, relation-rank campaign, logs, or descent is constructed",
        ],
        "pass": True,
    }


def main():
    print(json.dumps(run(), indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
