

# This file was *autogenerated* from the file p1553_pair_compositum_toy_r17a.sage
from sage.all_cmdline import *   # import sage library

_sage_const_193 = Integer(193); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_44 = Integer(44); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_103 = Integer(103); _sage_const_184 = Integer(184); _sage_const_62 = Integer(62); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6)
import json

F = GF(_sage_const_193 )
E = EllipticCurve(F, [_sage_const_2 , _sage_const_3 ])
P = E(_sage_const_1 , _sage_const_44 )
d = _sage_const_3 
endpoint_scalars = [_sage_const_1 , _sage_const_2 , _sage_const_3 ]
endpoints = [j * P for j in endpoint_scalars]
endpoint_x = [F(A[_sage_const_0 ]) for A in endpoints]

R0 = PolynomialRing(F, "x")
x = R0.gen()
psi_num = prod(x - a for a in endpoint_x)
psi_den = x**_sage_const_3  + _sage_const_5  * x + _sage_const_7 
derivative_num = psi_num.derivative() * psi_den - psi_num * psi_den.derivative()

assert P.order() == _sage_const_103 
assert endpoint_x == [F(_sage_const_1 ), F(_sage_const_184 ), F(_sage_const_62 )]
assert gcd(psi_num, psi_den) == _sage_const_1 
assert all(psi_den(a) != _sage_const_0  for a in endpoint_x)
assert gcd(derivative_num, derivative_num.derivative()) == _sage_const_1 
assert (psi_num - psi_den).degree() == _sage_const_2 

Rq = PolynomialRing(F, "q")
q = Rq.gen()
K = Rq.fraction_field()
S = PolynomialRing(K, "X")
X = S.gen()


def curve_rhs(value):
    return value**_sage_const_3  + _sage_const_2  * value + _sage_const_3 


def lift_base_polynomial(poly):
    return sum(K(poly[i]) * X**i for i in range(poly.degree() + _sage_const_1 ))


psi_num_X = lift_base_polynomial(psi_num)
psi_den_X = lift_base_polynomial(psi_den)


def branch_map(a):
    a = K(a)
    delta = K(q) - a
    c = -(K(q) + a)
    rhs_sum = curve_rhs(K(q)) + curve_rhs(a)
    addition_trace = _sage_const_2  * rhs_sum / delta**_sage_const_2  + _sage_const_2  * c
    quotient = K(q) ** _sage_const_2  + a * K(q) + a**_sage_const_2  + _sage_const_2 
    addition_norm = quotient**_sage_const_2  / delta**_sage_const_2  + _sage_const_2  * c * rhs_sum / delta**_sage_const_2  + c**_sage_const_2 
    quadratic = X**_sage_const_2  - addition_trace * X + addition_norm
    p_rem = psi_num_X % quadratic
    r_rem = psi_den_X % quadratic
    p0, p1 = K(p_rem[_sage_const_0 ]), K(p_rem[_sage_const_1 ])
    r0, r1 = K(r_rem[_sage_const_0 ]), K(r_rem[_sage_const_1 ])
    denominator_norm = r1**_sage_const_2  * addition_norm + r1 * r0 * addition_trace + r0**_sage_const_2 
    value_norm = (p1**_sage_const_2  * addition_norm + p1 * p0 * addition_trace + p0**_sage_const_2 ) / denominator_norm
    value_trace = (
        (p1 * r0 + p0 * r1) * addition_trace
        + _sage_const_2  * p1 * r1 * addition_norm
        + _sage_const_2  * p0 * r0
    ) / denominator_norm
    return K(value_trace), K(value_norm)


branch_maps = [branch_map(a) for a in endpoint_x[:_sage_const_2 ]]


def psi(value):
    return F(psi_num(value)) / F(psi_den(value))


direct_checks = []
for endpoint_index, A in enumerate(endpoints[:_sage_const_2 ]):
    trace_map, norm_map = branch_maps[endpoint_index]
    for scalar in [_sage_const_4 , _sage_const_5 , _sage_const_6 ]:
        Q = scalar * P
        plus = psi(F((A + Q)[_sage_const_0 ]))
        minus = psi(F((A - Q)[_sage_const_0 ]))
        q_value = F(Q[_sage_const_0 ])
        assert trace_map(q_value) == plus + minus
        assert norm_map(q_value) == plus * minus
        direct_checks.append([int(endpoint_scalars[endpoint_index]), int(scalar)])

B = PolynomialRing(F, names=("q0", "q1"))
q0, q1 = B.gens()


def lift_univariate(poly, variable):
    poly = Rq(poly)
    return sum(B(poly[i]) * variable**i for i in range(poly.degree() + _sage_const_1 ))


def equality_polynomial(function):
    numerator = Rq(function.numerator())
    denominator = Rq(function.denominator())
    return (
        lift_univariate(numerator, q0) * lift_univariate(denominator, q1)
        - lift_univariate(numerator, q1) * lift_univariate(denominator, q0)
    )


equalities = []
for trace_map, norm_map in branch_maps:
    equalities.append(equality_polynomial(trace_map))
    equalities.append(equality_polynomial(norm_map))

diagonal = q0 - q1
assert all(poly % diagonal == _sage_const_0  for poly in equalities)
common = equalities[_sage_const_0 ]
for poly in equalities[_sage_const_1 :]:
    common = gcd(common, poly)

factorization = [(str(factor), int(multiplicity)) for factor, multiplicity in factor(common)]
off_diagonal = common
while off_diagonal % diagonal == _sage_const_0 :
    off_diagonal //= diagonal
off_diagonal_is_constant = off_diagonal.total_degree() == _sage_const_0 

report = {
    "schema": "crypto.autoresearch.exact_toy_report.v1",
    "report_id": "P1553-PAIR-COMPOSITUM-TOY-R17A-REPORT",
    "date": "2026-07-19",
    "classification": ["toy", "exact", "model-bound", "novelty-unverified"],
    "field": _sage_const_193 ,
    "curve_order": int(E.order()),
    "subgroup_order": int(P.order()),
    "endpoint_x": [int(a) for a in endpoint_x],
    "psi_numerator": str(psi_num),
    "psi_denominator": str(psi_den),
    "derivative_numerator": str(derivative_num),
    "derivative_squarefree": True,
    "infinity_unramified": True,
    "fiber_uniform_min_support_lower_bound": _sage_const_2 ,
    "non_galois_degree_three": True,
    "direct_formula_checks": direct_checks,
    "paired_endpoints": [_sage_const_1 , _sage_const_2 ],
    "equality_total_degrees": [int(poly.total_degree()) for poly in equalities],
    "common_gcd_total_degree": int(common.total_degree()),
    "common_gcd_factorization": factorization,
    "off_diagonal_is_constant": bool(off_diagonal_is_constant),
    "decision": "REJECT_TOY_CANDIDATE_BIRATIONAL_PAIR" if off_diagonal_is_constant else "RETAIN_OFF_DIAGONAL_FACTOR_FOR_REVIEW",
    "breakthrough": False,
    "shoup_bound_improvement": False,
    "scope": "One fixed degree-three exact toy; no asymptotic, finite-deck, target, R10, rank, log, or descent claim.",
}

print(json.dumps(report, indent=_sage_const_2 , sort_keys=True))

